<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm22.aspx.cs" Inherits="WelsMain.WebForm22" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title></title>

    <link href="Content/bootstrap.css" rel="stylesheet" />
    <script src="Scripts/jquery-1.10.2.js"></script>
    <script src="Scripts/bootstrap.js"></script>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:GridView ID="GridView1" runat="server"
                ItemType="WelsMain.Personen"
                SelectMethod="GridView1_GetData"
                UpdateMethod="GridView1_UpdateItem"
                DataKeyNames="PersonID" AutoGenerateColumns="false"
                AutoGenerateEditButton="false" AutoGenerateDeleteButton="false" AutoGenerateSelectButton="false"
                CssClass="table table-bordered"
                AllowPaging="true" PageSize="5" PagerSettings-Mode="NextPreviousFirstLast">
                <PagerTemplate>
                    <ul class="pagination">
                        <li>
                            <asp:LinkButton runat="server" CommandName="Page" CommandArgument="First">
                           <span class="glyphicon glyphicon-step-backward"></span>
                            </asp:LinkButton></li>
                        <li>
                            <asp:LinkButton runat="server" CommandName="Page" CommandArgument="Prev">
                           <span class="glyphicon glyphicon-chevron-left"></span>
                            </asp:LinkButton></li>
                        <li>
                            <asp:LinkButton runat="server" CommandName="Page" CommandArgument="Next">
                           <span class="glyphicon glyphicon-chevron-right"></span>
                            </asp:LinkButton></li>
                        <li>
                            <asp:LinkButton runat="server" CommandName="Page" CommandArgument="Last">
                           <span class="glyphicon glyphicon-step-forward"></span>
                            </asp:LinkButton></li>
                    </ul>


                </PagerTemplate>
                <Columns>
                    <asp:TemplateField>
                        <ItemTemplate>
                            <asp:Button runat="server" CssClass="btn btn-default" CommandName="Edit" Text="E" />
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:Button runat="server" CssClass="btn btn-default" CommandName="Update" Text="S" />
                        </EditItemTemplate>
                    </asp:TemplateField>
                    <asp:BoundField DataField="Name" ControlStyle-CssClass="form-control" />
                </Columns>

            </asp:GridView>

        </div>
    </form>
</body>
</html>
